[project]
name = "PyRocketSim"
version = "0.1"
dependencies = ["matplotlib"]

[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.15", "pybind11>=2.6"]
build-backend = "setuptools.build_meta"