[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "cmake>=3.15",
    "pybind11>=2.6",
]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-frontend = "build"
manylinux-x86_64-image = "manylinux2014"
test-command = "python -c \"import PyRocketSim; PyRocketSim.__version__\""

[tool.cibuildwheel.linux]
before-build = "yum install -y python3-devel || apt-get install -y python3-dev || true"

[tool.cibuildwheel.macos]
test-skip = "*"  # Пропустить тесты на macOS если есть проблемы