[project]
name = "PyRocketSim"
version = "0.1"
dependencies = ["matplotlib"]

[build-system]
requires = ["setuptools", "wheel", "cmake>=3.15", "pybind11"]
build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
build-frontend = "build"

# Для Linux
manylinux-x86_64-image = "manylinux_2_28"

# Для Windows
test-command = "python -c \"import PyRocketSim; PyRocketSim.__version__\""